# Generated by Django 5.2.5 on 2025-10-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='telegram_photos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='telegram_audios/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
