# Generated by Django 5.2.5 on 2025-09-25 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0002_product_image_product_stock_product_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='gemini-embedding-001', max_length=100)),
                ('vector', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='market.product')),
            ],
        ),
    ]
